export { default as Article } from './Article/Article'
export { default as ArticleCard } from './ArticleCard/ArticleCard'
export { default as Link } from './Link/Link'
export { default as FronPage } from './FrontPage/Front.page'
export { default as ArticlePage } from './ArticlePage/Article.page'
export { default as Footer } from './Footer/Footer'
export { default as UserTermsPage } from './UserTermsPage/UserTerms.page'
